[project]
name = "xmpkit-py"
version = "0.1.2"
description = "Python bindings for xmpkit (Rust)"
authors = [{ name = "Adrien Bachelart", email = "hello@adrienbc.com" }]
maintainers = [{ name = "Adrien Bachelart", email = "hello@adrienbc.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Rust",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Software Development :: Libraries",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/adbac/xmpkit-py"
Issues = "https://github.com/adbac/xmpkit-py/issues"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]

[tool.maturin.generate-ci.github]
trusted-publishing = true
publishing-environment = "publish-to-pypi"
all = "All"

[dependency-groups]
dev = ["maturin>=1.14.1", "mkdocstrings-python>=2.0.5", "zensical>=0.0.53"]