from typing import Final

XMP: Final[str] = "http://ns.adobe.com/xap/1.0/"
"""XMP Basic namespace"""
DC: Final[str] = "http://purl.org/dc/elements/1.1/"
"""Dublin Core namespace"""
EXIF: Final[str] = "http://ns.adobe.com/exif/1.0/"
"""EXIF namespace"""
EXIF_AUX: Final[str] = "http://ns.adobe.com/exif/1.0/aux/"
"""EXIF Aux namespace"""
EXIF_EX: Final[str] = "http://cipa.jp/exif/1.0/"
"""EXIF 2.32 Extension namespace"""
IPTC_CORE: Final[str] = "http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
"""IPTC Core namespace"""
IPTC_EXT: Final[str] = "http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
"""IPTC Extension namespace"""
PHOTOSHOP: Final[str] = "http://ns.adobe.com/photoshop/1.0/"
"""Photoshop namespace"""
CAMERA_RAW: Final[str] = "http://ns.adobe.com/camera-raw-settings/1.0/"
"""Camera Raw namespace"""
XMP_RIGHTS: Final[str] = "http://ns.adobe.com/xap/1.0/rights/"
"""XMP Rights namespace"""
XMP_MM: Final[str] = "http://ns.adobe.com/xap/1.0/mm/"
"""XMP Media Management namespace"""
XMP_BJ: Final[str] = "http://ns.adobe.com/xap/1.0/bj/"
"""XMP Basic Job Ticket namespace"""
TIFF: Final[str] = "http://ns.adobe.com/tiff/1.0/"
"""TIFF namespace"""
PDF: Final[str] = "http://ns.adobe.com/pdf/1.3/"
"""PDF namespace"""
PDFX: Final[str] = "http://ns.adobe.com/pdfx/1.3/"
"""PDF/X namespace"""
PDFA: Final[str] = "http://www.aiim.org/pdfa/ns/id/"
"""PDF/A namespace"""
XMP_DM: Final[str] = "http://ns.adobe.com/xmp/1.0/DynamicMedia/"
"""XMP Dynamic Media namespace"""
XMP_PAGED: Final[str] = "http://ns.adobe.com/xap/1.0/t/pg/"
"""XMP PagedText namespace"""
XMP_GRAPHICS: Final[str] = "http://ns.adobe.com/xap/1.0/g/"
"""XMP Graphics namespace"""
XMP_IMAGE: Final[str] = "http://ns.adobe.com/xap/1.0/g/img/"
"""XMP Image namespace"""
RDF: Final[str] = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
"""RDF namespace"""
XML: Final[str] = "http://www.w3.org/XML/1998/namespace"
"""XML namespace (for xml:lang, etc.)"""
XMP_PREFIX: Final[str] = "xmp"
"""XMP namespace prefix"""
DC_PREFIX: Final[str] = "dc"
"""Dublin Core prefix"""
EXIF_PREFIX: Final[str] = "exif"
"""EXIF prefix"""
RDF_PREFIX: Final[str] = "rdf"
"""RDF prefix"""
XML_PREFIX: Final[str] = "xml"
"""XML prefix"""
EXIF_AUX_PREFIX: Final[str] = "aux"
"""EXIF Aux prefix"""
EXIF_EX_PREFIX: Final[str] = "exifEX"
"""EXIF 2.32 Extension prefix"""
IPTC_CORE_PREFIX: Final[str] = "Iptc4xmpCore"
"""IPTC Core prefix"""
IPTC_EXT_PREFIX: Final[str] = "Iptc4xmpExt"
"""IPTC Extension prefix"""
PHOTOSHOP_PREFIX: Final[str] = "photoshop"
"""Photoshop prefix"""
CAMERA_RAW_PREFIX: Final[str] = "crs"
"""Camera Raw prefix"""
XMP_RIGHTS_PREFIX: Final[str] = "xmpRights"
"""XMP Rights prefix"""
XMP_MM_PREFIX: Final[str] = "xmpMM"
"""XMP Media Management prefix"""
XMP_BJ_PREFIX: Final[str] = "xmpBJ"
"""XMP Basic Job Ticket prefix"""
TIFF_PREFIX: Final[str] = "tiff"
"""TIFF prefix"""
PDF_PREFIX: Final[str] = "pdf"
"""PDF prefix"""
PDFX_PREFIX: Final[str] = "pdfx"
"""PDF/X prefix"""
PDFA_PREFIX: Final[str] = "pdfaid"
"""PDF/A prefix"""
XMP_DM_PREFIX: Final[str] = "xmpDM"
"""XMP Dynamic Media prefix"""
XMP_PAGED_PREFIX: Final[str] = "xmpTPg"
"""XMP PagedText prefix"""
XMP_GRAPHICS_PREFIX: Final[str] = "xmpG"
"""XMP Graphics prefix"""
XMP_IMAGE_PREFIX: Final[str] = "xmpGImg"
"""XMP Image prefix"""
